language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EFFnxQXvBpEKvhI2Y2+D3ausQpzlOTsLTLbnAnzvzMxHGd0Yjq1DJ39Vo7n9wuWmsEUM6L8N2YuJgcTAV5dg/srFHEYAbNQTXisr306wS+uyMDacyHvcPeGwrQFp4mfua0S4ViwDqCkaLsWW98UkXeMYCD+JqdZpwzdsjwR89uQ="

addons:
  coverity_scan:
    project:
      name: "konradrenner/KoreMenuAPI"
      description: "Your project description here"
    notification_email: koni.renner@gmail.com
    build_command_prepend:
    build_command: mvn  install -DskipTests=true -B -V
    branch_pattern: master
